README.md, client/README.md, client/package.json, client/src/extension.ts, server/src/parser.ts, server/src/server.ts
=> add properties settings

README.md, client/README.md, client/package.json, client/src/extension.ts, server/src/server.ts
=> Add the enable/disable configuration

README.md, client/README.md, client/package-lock.json, client/package.json, client/src/extension.ts, package-lock.json, server/src/server.ts
=> can trigger checkstyle through command

README.md, client/README.md, client/package-lock.json, client/package.json, client/src/IUserInterface.ts, client/src/VSCodeUI.ts, client/src/command/checkCodeWithCheckstyle.ts, client/src/command/userSettings.ts, client/src/extension.ts
=> Enable set user settings

README.md, client/.vscodeignore, client/README.md, client/package.json, client/src/extension.ts, server/src/server.ts
- rename setting ```enable``` to ```autocheck```
- update the checkstyle version from 8.4 to 8.5
- refine the .vscodeignore
- refine README.md
=> rename enable setting to autocheck, update checkstyle from 8.4 to 8.5

README.md, client/README.md, client/package-lock.json, client/package.json, client/src/extension.ts, client/src/utils/downloadCheckstyle.ts, server/package.json, server/src/server.ts
=> download checkstyle-8.0-all.jar when it not exists

client/src/extension.ts
=> not pop up error message when the error is UserCancelledError

README.md, client/README.md, client/package.json, client/src/command/userSettings.ts, client/src/extension.ts, client/src/utils/downloadCheckstyle.ts, tslint.json
=> can set autocheck through command

README.md, client/README.md, client/package.json, client/src/command/userSettings.ts, client/src/extension.ts
=> can set properties file through command

README.md, client/README.md, client/package.json, client/src/extension.ts, client/src/utils/downloadCheckstyle.ts, server/src/server.ts
- show download status in status bar
- set autocheck default value to false
=> refine download status

client/package-lock.json, client/package.json, server/package-lock.json, server/package.json, server/src/checker.ts, server/src/checkstyleSetting.ts, server/src/downloadCheckstyle.ts, server/src/errors.ts, server/src/server.ts, server/src/serverRequests.ts
This is the second part for #18
=> Auto resolve version - server part

client/src/StatusController.ts, client/src/extension.ts, client/src/notifications.ts, server/src/notifications.ts, server/src/server.ts
The checkstyle status bar icon should be hidden when the server status is not running.
=> hide status bar icon when checkstyle server is not in running status

client/src/command/userSettings.ts
=> fix undefined error when no workspace is opened in vscode

client/src/command/userSettings.ts
make updateSettings() able to update multiple settings in one call
=> make updateSettings() able to update multiple settings in one call

client/package-lock.json, client/package.json, client/src/ICheckStyleSettings.d.ts, client/src/checkStyleSetting.ts, client/src/command/userSettings.ts, client/src/extension.ts, server/src/checker.ts
implement: #43 
Extract the properties in the Checkstyle configuration (if it has). Open an initialized file for the properties.
=> resolve property names

client/package-lock.json, package-lock.json, server/package-lock.json, server/src/checker.ts
=> fix issue #61

client/src/command/setCheckstyleConfig.ts, server/src/server.ts
=> fix #74, #75

client/package-lock.json, client/package.json, client/src/DialogResponses.ts, client/src/command/setCheckstyleVersion.ts, client/src/extension.ts, client/src/notifications.ts, server/src/downloadCheckstyle.ts, server/src/notifications.ts
=> can let user open the download page when auto download failed

client/CHANGELOG.md
=> refine the changelog

client/src/StatusController.ts, client/src/extension.ts, client/src/notifications.ts, server/src/notifications.ts, server/src/server.ts
=> add a new checkstyle status icon to indicate language server error

client/package.json, client/src/DialogResponses.ts, client/src/extension.ts
=> user can disable showing the invalid version hint

README.md, client/CHANGELOG.md, client/README.md, client/package.json
=> refine extension command names

server/src/downloadCheckstyle.ts
=> fix response undefined error

client/src/StatusController.ts, client/src/extension.ts, client/src/notifications.ts, server/src/downloadCheckstyle.ts, server/src/notifications.ts, server/src/server.ts
=> Refine the status bar icon

client/package-lock.json, client/package.json
=> update npm package

client/package-lock.json, client/package.json, client/src/StatusController.ts, client/src/command/checkCodeWithCheckstyle.ts, client/src/command/clearCheckstyleViolation.ts, client/src/extension.ts, package-lock.json, server/package-lock.json
=> Support clear checkstyle violation

client/package-lock.json, client/package.json, package-lock.json, server/package-lock.json
fix: #118 
Signed-off-by: Sheng Chen <sheche@microsoft.com>
=> disable checkstyle command showing in the output channel context menu

server/src/downloadCheckstyle.ts
=> download checkstyle from github

client/README.md
=> change the link to absolute rather than relative

client/package-lock.json, client/package.json, package-lock.json, server/package-lock.json
=> fix vulnerabilities

.vscodeignore, CONTRIBUTING.md, server/package.json
=> add contributing

src/utils/errorUtils.ts
To provide more information to users.
=> Print the data field if it's available in the error object

src/commands/check.ts, src/extension.ts
Fix #149 
I was trying to figure out if there is a way to simplify the code. This is the best of what I can do for now.
=> Fix the bug that failed to check code when auto-check is off

README.md
=> Fix the wrong default value for 'java.checkstyle.autocheck'

jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/runner/CheckstyleRunner.java
=> [bugfix] Fix could not run Checkstyle on Java 11

package-lock.json, package.json, src/checkstyleDiagnosticManager.ts, src/extension.ts, src/features/FileSynchronizer.ts
Covered Issue: #175 
Feature implemented:
* Temp file synchronizer with batch flushing
* Diagnostic manager with live linting support (one document per check)
* Debounced diagnostic request to prevent IO thrashing
=> Support live linting

src/checkstyleDiagnosticManager.ts, src/features/FileSynchronizer.ts
=> Enhanced live-linting

jdtls.ext/com.shengchen.checkstyle.runner/plugin.xml, jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/runner/CheckstyleExecutionListener.java, jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/runner/CheckstyleRunner.java, jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/runner/handler/DelegateCommandHandler.java, package.json, package.nls.json, package.nls.zh.json, src/checkstyleDiagnosticManager.ts, src/commands/check.ts, src/constants/commands.ts, src/extension.ts, src/utils/settingUtils.ts, tsconfig.json
=> feat: Support batch checking

src/checkstyleDiagnosticCollector.ts, src/checkstyleStatusBar.ts
Fix #194 by improving status bar mechanism.
=> fix: The status bar item is not update correctly

src/checkstyleDiagnosticManager.ts, src/extension.ts, src/features/FileSynchronizer.ts
=> fix: Refresh server when configuration file is created, changed or deleted

package-lock.json, package.json, src/extension.ts, src/utils/settingUtils.ts, webpack.config.js
=> fix: Support listening to configuration file outside of workspace

package-lock.json, package.json, src/commands/config.ts, src/constants/checkstyleConfigs.ts, src/extension.ts, src/utils/settingUtils.ts
=> feat: Improved setConfiguration command with automatic configuration detection

src/checkstyleStatusBar.ts
=> feat: Open the Problems panel when click the status icon in the status bar

src/constants/checkstyleConfigs.ts
=> fix: Add more public doctype id for config detection

CONTRIBUTING.md, jdtls.ext/com.shengchen.checkstyle.runner/target.target
=> doc: Add contribution page

jdtls.ext/com.shengchen.checkstyle.runner/pom.xml, jdtls.ext/pom.xml
https://www.eclipse.org/m2e/documentation/release-notes-17.html#new-syntax-for-specifying-lifecycle-mapping-metadata
=> Use modern m2e ignore

jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/quickfix/BaseQuickFix.java, jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/quickfix/coding/MultipleVariableDeclarationsQuickFix.java
For variable declaration statements
Replacement for #303
=> Fix MultipleVariableDeclarationsQuickFix comment handling

src/features/FileSynchronizer.ts
=> fix: Generate temp files according to the folder structure

jdtls.ext/com.shengchen.checkstyle.checker/src/main/java/com/shengchen/checkstyle/checker/CheckerListener.java, jdtls.ext/config/checkstyle.xml, jdtls.ext/pom.xml, package-lock.json
Resolves #322
**PS**: I recreated the `package-lock.json` file because it was not compatible anymore with newer versions of NPM. However, as this can present more changes, I can remove the change from this PR 🙂
=> perf(checkstyle): Compatibility for v8.42+

src/extension.ts
fix https://github.com/jdneo/vscode-checkstyle/issues/343
fix https://github.com/jdneo/vscode-checkstyle/issues/341
=> fix: Wait for JLS ready event

jdtls.ext/com.shengchen.checkstyle.target/target.target
=> build: Update target platform

jdtls.ext/com.shengchen.checkstyle.target/target.target
Fixes issue: https://github.com/jdneo/vscode-checkstyle/issues/360
=> [#360] Update to release repository 2023-12

.vscode/launch.json
=> Add projectName to launch.json
