jdneo/vscode-checkstyle

- client/src/StatusController.ts
Fix #99 
Root cause: 
What we need here is check if the status is `undefined`, but the value of `CheckStatus.success` is 0, so it become true after `! statusValue `
> fix the status bar bug

- src/extension.ts
Change the event listener to make sure the extension will check the code when switching the active editor
Fix #151
> Make the extension will check the code when switching the active editor

- src/checkstyleDiagnosticCollector.ts
- src/checkstyleStatusBar.ts
- src/commands/check.ts
- src/constants/commands.ts
- src/extension.ts
- src/utils/errorUtils.ts
Fix #155
Instead of keep popping up a dialog to the user. We use the status bar to show the current status of the Checkstyle.
- If no violation, it will show a check
- If having violation(s), it will show a bug
- If an internal error occurs, it will show a stop sign. If the user clicks on the stop sign, we will open the output channel.
> Add status bar

- src/commands/check.ts
Fix #181 
To support loading checkstyle config via http url, we only need to remove the path checking in ts extension side.
Clarification:
1. Checkstyle‘s [`LoadConfiguration`](https://github.com/checkstyle/checkstyle/blob/2a54aad3f3cf01d98940a4ea86500fff3af3cce2/src/main/java/com/puppycrawl/tools/checkstyle/ConfigurationLoader.java#L392) method already supports loading via a http URL:
```java
loadConfiguration(String config, ...) {
// figure out if this is a File or a URL
final URI uri = CommonUtil.getUriByFilename(config);
final InputSource source = new InputSource(uri.toString());
return loadConfiguration(source, overridePropsResolver,
ignoredModulesOptions, threadModeSettings);
}
```
2. Checkstyle already provided a [path checking …
> Supports loading checkstyle config via http url

- src/features/FileSynchronizer.ts
* Rename `pending` -> `pendingRequests`
* Ensure the temp file as well as its directory exists before writing
> fix: Ensure the temp file as well as its directory exists before writing

- jdtls.ext/com.shengchen.checkstyle.runner/plugin.xml
- jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/runner/CheckstyleExecutionListener.java
- jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/runner/CheckstyleRunner.java
- package.json
- package.nls.json
- package.nls.zh.json
- src/checkstyleDiagnosticManager.ts
- src/commands/setCheckstyleConfiguration.ts
- src/constants/commands.ts
- src/extension.ts
* Make checker & listener static
* Add `setConfiguration` command as initialization process;
* Diagnostic manager now disposable, making it possible to skip the check as well as file sync when configuration file not set.
> perf: Static checker in Java server

- src/features/FileSynchronizer.ts
Fix #192 by keeping temp file's name the same with original file and saved in a singleton temp folder.
> fix: Keep the temp file's name the same with original file

- gulpfile.js
- package-lock.json
- package.json
gulp-download is not maintain for a long time. Cause security vulnerability now.
> chore: Migrate to gulp-remote-src

- src/utils/settingUtils.ts
> fix: Manually specify null when resource uri is none

- CHANGELOG.md
- src/checkstyleConfigurationManager.ts
- src/commands/config.ts
`Uri.file` will parse "" to "/".
> fix: BAD uri lacks scheme warning when the config is empty

- .vscode/extensions.json
- .vscode/settings.json
- package-lock.json
- package.json
- src/checkstyleConfigurationManager.ts
For now, the newest typescript version is 3.6.2, where a stricter type deduction is performed. In such case, if a developer globally uses the newer version, the `tsc` command won't pass. 
Environment:
1. The typescript version specified in package.lock.json is 3.2.2
2. The typescript version used by vscode is 3.5.2
3. The typescript version globally installed is 3.6.2
In such case:
1. TS's language service in vscode uses 3.5.2 (by default, overriden by `typescript.tsdk` setting)
2. package.json's `npm run compile` uses 3.6.2 (no idea why not use version specified in lock).
3. Version 3.6.2 will complain a TypeError, which will pass in 3.5.2.
4. As a result, vscode editor does not complain any error, but project fails to compile.
> chore: Update typescript version & extension recommendation

- src/checkstyleDiagnosticManager.ts
It is to ensure that diagnostic service can only be enabled after configuraiton has been successfully set.
> fix: Diagnostic manager should be disabled at the beginning

- src/checkstyleConfigurationManager.ts
It is because everytime refreshing, a new chokidar watcher is set to watch the config file, when a new 'add' event is emitted after intialization, causing a new refresh.
Problems raised by it:
* ConcurrentModificationException
* Error log pop up twice when there's error in module initialization
> fix: setConfiguration request is sent twice every time refreshing

- src/utils/errorUtils.ts
When checkstyle version is higher than 8.2x, there's more detailed output for module initialzation failure:
`cannot initialize module TreeWalker - cannot initialize module LineLength...`
Currently, a non-greedy capture is adopted to only capture the first module. In the future we may consider to parse the output to give a more detailed error message.
> fix: Add nullcheck and non-greedy capture when handling module initialization error

- src/utils/settingUtils.ts
The cause: `resolveVariables` should not provide default value for resourceUri.
> fix: ${workspaceFolder}/.../checkstyle.xml not found

- src/commands/config.ts
> fix: XML parsing error in xml2js will stop the entire detection process

- src/commands/check.ts
- src/commands/config.ts
- src/constants/checkstyleConfigs.ts
- src/utils/settingUtils.ts
- src/utils/workspaceUtils.ts
Fix #242 
`workspace.findFiles` by default will **NOT** exclude `node_modules`, because it only uses `files.exclude` setting, where `node_modules` is in `search.exclude` and `.gitignore`.
- **reference**: https://github.com/Microsoft/vscode/issues/48674, an problem which is aware of by vscode team
- **fix**: Introduce a new funciton, excludes all of `files.exclude`, `search.exclude` and `.gitignore`, like https://github.com/Microsoft/vscode/issues/48674#issuecomment-422950502
> fix: node_modules will be searched when detecting configuration

- jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/checker/CheckerService.java
- jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/runner/DelegateCommandHandler.java
Some efforts are put to improve the stabillity of checkstyle server:
* dispose guarantees success no matter whether checker or listener is null
* delegate command handler is now synchronied per-request-scale
* checkerService will be set to null upon initialization failed, indicating that currently server cannot provide checkstyle realated service:
* `getVersion` will return null
* `checkCode` will return empty map
* Intialized checker will be disposed to prevent memory leak
Other changes:
* every command handler is now set protected rather than public
> refactor: Checkstyle server stability

- src/checkstyleConfigurationManager.ts
- src/commands/version.ts
Fix #227 
Now the `setVersion` command's getting latest version and list all versions functionality will try to use github api data from local disk, and secretly update the data once fetched. If not exist on local disk, then fetch from github and save.
> perf: Use local api data first to provide version information

- jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/checker/CheckerService.java
Fix #245 
This is because the project with no .classpath will not be recognized as JavaProject in `resolveCompilationUnit` and null is returned. We could directly use `findFile` to get the project.
~~However `resolveCompilationUnit` should still be preserved, as the temp file is not in a project and `findFile` will also return null, while `resolveCompilationUnit` will create a fake one for it.~~
`resolveCompilationUnit` is completely removed now.
> fix: Java project with no .classpath file will result in NullPointerException

- jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/runner/CheckstyleLoader.java
> fix: Plugin jar load failed when jar path containing whitespace

- jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/runner/CheckstyleLoader.java
- jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/runner/DelegateCommandHandler.java
- package.json
- package.nls.json
- package.nls.zh.json
- src/checkstyleConfigurationManager.ts
- src/constants/settings.ts
- src/models.ts
- src/utils/settingUtils.ts
Fix #206 
Example usage:
```json
"java.checkstyle.modules": [
"${workspaceFolder}/src/main/resources/sevntu-checks-1.35.0.jar"
]
```
Add `<module name="SingleBreakOrContinueCheck"/>` or `<module name="com.github.sevntu.checkstyle.checks.naming.SingleBreakOrContinueCheck"/>` to `checkstyle.xml`, effect:
> feat: Support third-party extension checkstyle modules

- jdtls.ext/com.shengchen.checkstyle.checker/src/main/java/com/shengchen/checkstyle/checker/CheckerListener.java
This fixes the reported column of errors in VS Code in code that uses tab indentation.
CheckStyle has funny treatment of tabs. Its error.getColumn() returns a number that treats tabs as being however many spaces. Fortunately getolumnCharIndex() returns the correct value to send back to VS Code.
> Fix the error column that’s reported to VS Code

- jdtls.ext/com.shengchen.checkstyle.runner/src/main/java/com/shengchen/checkstyle/quickfix/modifier/RedundantModifierQuickFix.java
Particularly, remove `static` on inner `interface` definitions. But doesn't hurt to remove `abstract` on interfaces too!
(I'm on a mission to quick fix as many issues as possible in a large code base!)
> Remove redundant modifiers on interface declarations

- .gitignore
- .vscode/extensions.json
- .vscode/tasks.json
- CONTRIBUTING.md
- README.md
- jdtls.ext/com.shengchen.checkstyle.checker/pom.xml
- jdtls.ext/com.shengchen.checkstyle.runner/.classpath
- jdtls.ext/com.shengchen.checkstyle.runner/.project
- jdtls.ext/com.shengchen.checkstyle.runner/.settings/org.eclipse.core.resources.prefs
- jdtls.ext/com.shengchen.checkstyle.runner/.settings/org.eclipse.m2e.core.prefs
- jdtls.ext/com.shengchen.checkstyle.runner/META-INF/MANIFEST.MF
> build: Fix the extension setup issue
